# Site Settings
title: "Leobrqz"
description: "Portfolio website"
author: "Leonardo Briquezi"
github_username: "leobrqz"

# Language Settings
default_lang: pt
languages:
  - pt
  - en

# GitHub Pages Settings
baseurl: ""
url: "https://leonardobriquezi.me"

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include directories
include:
  - _pages

# Repository list for projects
repositories:
  - ShScriptHub
  - AutoPot-DR
  - SmokeShopERP-DataAnalytics
  - MiniSchool
  - Cheatsheet-LabAI
  - myContracts-SpeedrunEthereum

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - DevelopmentPlan